#!/usr/bin/env python3
"""
generate src/unicode_tables.h from python's unicodedata.

bits per codepoint:

  LETTER    : category starts with 'L'          (\\p{L})
  DIGIT     : category starts with 'N'          (\\p{N})
  SPACE     : codepoint has Unicode White_Space (\\s)
  NEWLINE   : U+000A or U+000D                  (\\r, \\n)
  UPPER     : category Lu or Lt                 (for o200k upper-class)
  LOWER     : category Ll                       (for o200k lower-class)
  MARK      : category starts with 'M'          (\\p{M}, for o200k)

UPPER/LOWER/MARK are additional bits needed by the o200k pre-tokenizer.
cl100k uses only LETTER/DIGIT/SPACE/NEWLINE.

o200k letter classes derived from these bits:
  upperish ([Lu Lt Lm Lo M])  == (LETTER & ~LOWER) | MARK
  lowerish ([Ll Lm Lo M])     == (LETTER & ~UPPER) | MARK

packed as a two-stage table:
  stage1[cp >> 8]            -> block index (u16)
  stage2[block][cp & 0xFF]   -> class bits  (u8)

duplicate 256-byte blocks are deduplicated. more bits means more
distinct blocks; expect stage2 to grow from ~32 KiB to ~50-80 KiB.
"""
import sys
import unicodedata
from pathlib import Path

# use the `regex` module instead of `unicodedata` so our classification
# matches what tiktoken's Rust regex engine sees. the Rust `regex` crate
# and Python's `regex` module both classify unassigned codepoints inside
# letter blocks (e.g. U+13C88) as \p{L}/\p{Lo}, while Python's
# `unicodedata.category()` returns 'Cn'. that discrepancy caused real
# fuzz mismatches on o200k.
import regex as _rx

_re_L  = _rx.compile(r"\p{L}")
_re_N  = _rx.compile(r"\p{N}")
_re_M  = _rx.compile(r"\p{M}")
_re_Lu = _rx.compile(r"\p{Lu}")
_re_Lt = _rx.compile(r"\p{Lt}")
_re_Ll = _rx.compile(r"\p{Ll}")

MAX_CP = 0x110000  # codepoints 0 .. 0x10FFFF

LETTER  = 1 << 0
DIGIT   = 1 << 1
SPACE   = 1 << 2
NEWLINE = 1 << 3
UPPER   = 1 << 4
LOWER   = 1 << 5
MARK    = 1 << 6

# Unicode White_Space property (as of unicode 15). small fixed set.
WHITE_SPACE = set([
    0x0009, 0x000A, 0x000B, 0x000C, 0x000D,
    0x0020,
    0x0085,
    0x00A0,
    0x1680,
    0x2028, 0x2029,
    0x202F,
    0x205F,
    0x3000,
])
WHITE_SPACE.update(range(0x2000, 0x200B))  # en/em/etc spaces


def classify(cp: int) -> int:
    cls = 0
    try:
        ch = chr(cp)
    except ValueError:
        return 0
    if _re_L.match(ch):
        cls |= LETTER
    if _re_N.match(ch):
        cls |= DIGIT
    if cp in WHITE_SPACE:
        cls |= SPACE
    if cp == 0x0A or cp == 0x0D:
        cls |= NEWLINE
    if _re_Lu.match(ch) or _re_Lt.match(ch):
        cls |= UPPER
    if _re_Ll.match(ch):
        cls |= LOWER
    if _re_M.match(ch):
        cls |= MARK
    return cls


def build() -> tuple[list[int], list[int]]:
    # produce stage 2 block by block, deduplicating
    blocks: list[tuple[int, ...]] = []
    block_index: dict[tuple[int, ...], int] = {}
    stage1 = [0] * (MAX_CP >> 8)
    for top in range(MAX_CP >> 8):
        base = top << 8
        block = tuple(classify(base + i) for i in range(256))
        idx = block_index.get(block)
        if idx is None:
            idx = len(blocks)
            block_index[block] = idx
            blocks.append(block)
        stage1[top] = idx
    stage2: list[int] = []
    for b in blocks:
        stage2.extend(b)
    return stage1, stage2


def emit_header(stage1: list[int], stage2: list[int], out_path: str):
    n_blocks = len(stage2) // 256
    n_stage1 = len(stage1)
    max_block = n_blocks - 1
    stage1_type = "uint16_t" if max_block > 0xFF else "uint8_t"
    lines = []
    ap = lines.append
    ap("/* auto-generated by scripts/gen_unicode_tables.py. do not edit. */")
    ap("#ifndef X8R_UNICODE_TABLES_H")
    ap("#define X8R_UNICODE_TABLES_H")
    ap("")
    ap("#include <stdint.h>")
    ap("")
    ap("#define X8R_CLS_LETTER  0x01u")
    ap("#define X8R_CLS_DIGIT   0x02u")
    ap("#define X8R_CLS_SPACE   0x04u")
    ap("#define X8R_CLS_NEWLINE 0x08u")
    ap("#define X8R_CLS_UPPER   0x10u  /* Lu, Lt (for o200k)      */")
    ap("#define X8R_CLS_LOWER   0x20u  /* Ll    (for o200k)       */")
    ap("#define X8R_CLS_MARK    0x40u  /* M*    (for o200k)       */")
    ap("")
    ap("/* o200k letter classes derived from the bits above */")
    ap("#define X8R_CLS_O200K_UPPERISH(c) (((c) & (X8R_CLS_LETTER | X8R_CLS_LOWER)) == X8R_CLS_LETTER || ((c) & X8R_CLS_MARK))")
    ap("#define X8R_CLS_O200K_LOWERISH(c) (((c) & (X8R_CLS_LETTER | X8R_CLS_UPPER)) == X8R_CLS_LETTER || ((c) & X8R_CLS_MARK))")
    ap("")
    ap(f"#define X8R_UNI_STAGE1_LEN {n_stage1}")
    ap(f"#define X8R_UNI_STAGE2_BLOCKS {n_blocks}")
    ap("")
    ap(f"static const {stage1_type} x8r_uni_stage1[{n_stage1}] = {{")
    for i in range(0, n_stage1, 16):
        row = ", ".join(str(v) for v in stage1[i:i+16])
        ap(f"    {row},")
    ap("};")
    ap("")
    ap(f"static const uint8_t x8r_uni_stage2[{len(stage2)}] = {{")
    for i in range(0, len(stage2), 32):
        row = ", ".join(f"0x{v:x}" for v in stage2[i:i+32])
        ap(f"    {row},")
    ap("};")
    ap("")
    ap("static inline uint32_t x8r_cp_class(uint32_t cp) {")
    ap("    if (cp >= 0x110000u) return 0;")
    ap(f"    uint32_t block = x8r_uni_stage1[cp >> 8];")
    ap("    return x8r_uni_stage2[(block << 8) | (cp & 0xFFu)];")
    ap("}")
    ap("")
    ap("#endif")
    Path(out_path).write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path}: stage1={n_stage1} entries, stage2={n_blocks} blocks "
          f"({len(stage2)} bytes), total ~{(n_stage1 * (2 if stage1_type=='uint16_t' else 1) + len(stage2)) // 1024} KiB",
          file=sys.stderr)


if __name__ == "__main__":
    s1, s2 = build()
    out = sys.argv[1] if len(sys.argv) > 1 else "src/unicode_tables.h"
    emit_header(s1, s2, out)
